import json
import os

with open('messages/en.json', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

# Deep comprehensive translations for all UI keys
MARATHI_MAPPINGS = {
    # Greeting and Chat
    "Where would you like to start?": "आपण कुठून सुरुवात करू इच्छिता?",
    "Ask anything or @mention": "काहीही विचारा किंवा @mention करा",
    "Good morning": "शुभ प्रभात",
    "Good afternoon": "शुभ दुपार",
    "Good evening": "शुभ संध्याकाळ",
    "Nice to see you again": "तुम्हाला पुन्हा भेटून आनंद झाला",
    "What are you working on today": "आज तुम्ही कोणत्या विषयावर काम करत आहात?",
    "Let me know when you're ready to begin": "सुरुवात करायची असेल तेव्हा मला सांगा",
    "What are your thoughts today": "आज आपले काय विचार आहेत?",
    "What are you thinking": "तुम्ही काय विचार करत आहात?",
    "Chat Error": "चॅट त्रुटी",
    "This message was not saved. Please try the chat again.": "हा संदेश जतन केला गेला नाही. कृपया पुन्हा प्रयत्न करा.",
    "Upload File": "फाइल अपलोड करा",
    "Generate Image": "प्रतिमा तयार करा",
    "Image uploaded successfully": "प्रतिमा यशस्वीरित्या अपलोड झाली",
    
    # Layout and Sidebar
    "Workflow": "कार्यप्रवाह (Workflow)",
    "Admin": "प्रशासन (Admin)",
    "Users": "वापरकर्ते",
    "Toggle Sidebar": "साइडबार टॉगल करा",
    "New Chat": "नवीन चॅट",
    "MCP Configuration": "MCP कॉन्फिगरेशन",
    "Agents": "सागरी तज्ञ एजंट्स",
    "Create Agent": "एजंट तयार करा",
    "Create an agent": "एजंट तयार करा",
    "Create your own agent": "तुमचा स्वतःचा एजंट तयार करा",
    "Create your own specialized AI agent or select from shared agents in the Agents page": "तुमचा स्वतःचा विशेष सागरी AI एजंट तयार करा किंवा एजंट्स पृष्ठावरून निवडा",
    "Today": "आज (Today)",
    "Yesterday": "काल (Yesterday)",
    "Previous 7 Days": "मागील ७ दिवस",
    "Previous 30 Days": "मागील ३० दिवस",
    "Theme": "थीम (Theme)",
    "Language": "भाषा (Language)",
    "Settings": "सेटिंग्ज",
    "Profile": "प्रोफाइल",
    "Sign Out": "बाहेर पडा (Sign Out)",
    "Light": "लाइट",
    "Dark": "डार्क",
    "System": "सिस्टम",
    
    # MCP Page
    "Marketplace": "मार्केटप्लेस (Marketplace)",
    "MCP Servers": "MCP सर्व्हर्स",
    "Add Server": "सर्व्हर जोडा",
    "Add MCP Server": "MCP सर्व्हर जोडा",
    "Connect Your First Server": "तुमचा पहिला सर्व्हर कनेक्ट करा",
    "Add MCP servers to unlock powerful AI integrations": "शक्तिशाली सागरी AI एकत्रीकरण अनलॉक करण्यासाठी MCP सर्व्हर्स जोडा",
    "Available MCP Servers": "उपलब्ध MCP सर्व्हर्स",
    "Save Configuration": "कॉन्फिगरेशन जतन करा",
    "Tools Test": "साधने चाचणी",
    
    # Common
    "Cancel": "रद्द करा",
    "Update": "अपडेट करा",
    "Continue": "पुढे सुरू ठेवा",
    "Success": "यशस्वी",
    "Delete": "हटवा",
    "Save": "जतन करा",
    "Back": "मागे",
    "Next": "पुढे",
    "Create": "तयार करा",
    "Show less": "कमी दाखवा",
    "Show more": "अधिक दाखवा",
    "Generate": "निर्मिती करा",
    "Edit": "संपादित करा",
    "Edit Agent": "एजंट संपादित करा",
    "Search...": "शोधा...",
    "Approve": "मंजूर करा",
    "Reject": "नाकारा",
    "Saving...": "जतन करत आहे...",
    "Optional": "पर्यायी",
    "Deleting...": "हटवत आहे...",
    "Run": "चालवा",
    "Description": "वर्णन",
    "Default Value": "डीफॉल्ट मूल्य",
    "Empty": "रिकामे",
    "Required": "आवश्यक",
    "Options": "पर्याय",
    "Status": "स्थिती",
    "Result": "निकाल",
    "Started At": "सुरू झाले",
    "Duration": "कालावधी",
    "Add Option": "पर्याय जोडा",
    "Tool": "साधन (Tool)",
    "Select Tool...": "साधन निवडा...",
    "No results.": "कोणतेही निकाल आढळले नाहीत.",
    "Generate With AI": "AI सह तयार करा",
    
    # Archive
    "Archive": "अभिलेखागार (Archive)",
    "Add Archive": "संग्रह जोडा",
    "Archive Name": "संग्रहाचे नाव",
    "Archive Description": "संग्रह वर्णन",
    "No Archives": "कोणताही संग्रह आढळला नाही",
    
    # Agent
    "Generating Agent...": "एजंट तयार होत आहे...",
    "Give your agent a name and icon.": "तुमच्या एजंटला नाव आणि चिन्ह द्या.",
    "Add a brief description of what this agent does.": "हा एजंट काय करतो याचे संक्षिप्त वर्णन जोडा.",
    "This agent is": "हा एजंट आहे",
    "Expert in": "मधील तज्ञ",
}

HINDI_MAPPINGS = {
    "Where would you like to start?": "आप कहाँ से शुरुआत करना चाहेंगे?",
    "Ask anything or @mention": "कुछ भी पूछें या @mention करें",
    "Good morning": "शुभ प्रभात",
    "Good afternoon": "शुभ दोपहर",
    "Good evening": "शुभ संध्या",
    "Nice to see you again": "आपको दोबारा देखकर खुशी हुई",
    "What are you working on today": "आज आप किस पर काम कर रहे हैं?",
    "Let me know when you're ready to begin": "जब आप तैयार हों तो मुझे बताएं",
    "What are your thoughts today": "आज आपके क्या विचार हैं?",
    "What are you thinking": "आप क्या सोच रहे हैं?",
    "Chat Error": "चैट त्रुटि",
    "This message was not saved. Please try the chat again.": "यह संदेश सहेजा नहीं गया। कृपया पुनः प्रयास करें।",
    "Upload File": "फ़ाइल अपलोड करें",
    "Generate Image": "छवि उत्पन्न करें",
    "Image uploaded successfully": "छवि सफलतापूर्वक अपलोड हुई",
    "Workflow": "कार्यप्रवाह (Workflow)",
    "Admin": "प्रशासन (Admin)",
    "Users": "उपयोगकर्ता",
    "Toggle Sidebar": "साइडबार टॉगल करें",
    "New Chat": "नई चैट",
    "MCP Configuration": "MCP विन्यास",
    "Agents": "समुद्री विशेषज्ञ एजेंट",
    "Create Agent": "एजेंट बनाएं",
    "Create an agent": "एजेंट बनाएं",
    "Create your own agent": "अपना एजेंट बनाएं",
    "Create your own specialized AI agent or select from shared agents in the Agents page": "अपना विशेष समुद्री AI एजेंट बनाएं या एजेंट पेज से चुनें",
    "Today": "आज (Today)",
    "Yesterday": "कल (Yesterday)",
    "Previous 7 Days": "पिछले 7 दिन",
    "Previous 30 Days": "पिछले 30 दिन",
    "Theme": "थीम (Theme)",
    "Language": "भाषा (Language)",
    "Settings": "सेटिंग्स",
    "Profile": "प्रोफ़ाइल",
    "Sign Out": "साइन आउट",
    "Marketplace": "मार्केटप्लेस",
    "MCP Servers": "MCP सर्वर",
    "Add Server": "सर्वर जोड़ें",
    "Add MCP Server": "MCP सर्वर जोड़ें",
    "Connect Your First Server": "अपना पहला सर्वर कनेक्ट करें",
    "Add MCP servers to unlock powerful AI integrations": "शक्तिशाली समुद्री AI एकीकरण के लिए MCP सर्वर जोड़ें",
    "Cancel": "रद्द करें",
    "Update": "अपडेट करें",
    "Continue": "जारी रखें",
    "Success": "सफल",
    "Delete": "हटाएं",
    "Save": "सहेजें",
    "Back": "पीछे",
    "Next": "आगे",
    "Create": "बनाएं",
    "Search...": "खोजें...",
    "Tool": "उपकरण (Tool)",
    "Select Tool...": "उपकरण चुनें...",
    "Archive": "अभिलेखागार (Archive)",
    "Add Archive": "संग्रह जोड़ें",
}

GUJARATI_MAPPINGS = {
    "Where would you like to start?": "તમે ક્યાંથી શરૂ કરવા માંગો છો?",
    "Ask anything or @mention": "કંઈપણ પૂછો અથવા @mention કરો",
    "Good morning": "સુપ્રભાત",
    "Good afternoon": "શુભ બપોર",
    "Good evening": "શુભ સંધ્યા",
    "Workflow": "કાર્યપ્રવાહ (Workflow)",
    "Admin": "એડમિન (Admin)",
    "Users": "વપરાશકર્તાઓ",
    "Toggle Sidebar": "સાઇડબાર ટૉગલ કરો",
    "New Chat": "નવી ચેટ",
    "MCP Configuration": "MCP ગોઠવણી",
    "Agents": "દરિયાઈ નિષ્ણાત એજન્ટ્સ",
    "Create Agent": "એજન્ટ બનાવો",
    "Create an agent": "એજન્ટ બનાવો",
    "Create your own specialized AI agent or select from shared agents in the Agents page": "તમારો પોતાનો દરિયાઈ AI એજન્ટ બનાવો અથવા એજન્ટ પેજ પરથી પસંદ કરો",
    "Today": "આજે (Today)",
    "Yesterday": "ગઈકાલે (Yesterday)",
    "Previous 7 Days": "છેલ્લા 7 દિવસ",
    "Previous 30 Days": "છેલ્લા 30 દિવસ",
    "Theme": "થીમ (Theme)",
    "Language": "ભાષા (Language)",
    "Settings": "સેટિંગ્સ",
    "Profile": "પ્રોફાઇલ",
    "Sign Out": "સાઇન આઉટ",
    "Marketplace": "માર્કેટપ્લેસ",
    "MCP Servers": "MCP સર્વર્સ",
    "Add Server": "સર્વર ઉમેરો",
    "Add MCP Server": "MCP સર્વર ઉમેરો",
    "Connect Your First Server": "તમારો પ્રથમ સર્વર કનેક્ટ કરો",
    "Add MCP servers to unlock powerful AI integrations": "શક્તિશાળી દરિયાઈ AI સંકલન માટે MCP સર્વર્સ ઉમેરો",
    "Cancel": "રદ કરો",
    "Update": "અપડેટ કરો",
    "Continue": "ચાલુ રાખો",
    "Success": "સફળ",
    "Delete": "કાઢી નાખો",
    "Save": "સાચવો",
    "Back": "પાછળ",
    "Next": "આગળ",
    "Create": "બનાવો",
    "Search...": "શોધો...",
    "Archive": "સંગ્રહ (Archive)",
    "Add Archive": "સંગ્રહ ઉમેરો",
}

TAMIL_MAPPINGS = {
    "Where would you like to start?": "நீங்கள் எங்கிருந்து தொடங்க விரும்புகிறீர்கள்?",
    "Ask anything or @mention": "எதையும் கேளுங்கள் அல்லது @mention செய்யவும்",
    "Good morning": "காலை வணக்கம்",
    "Good afternoon": "மதிய வணக்கம்",
    "Good evening": "மாலை வணக்கம்",
    "Workflow": "பணிப்பாய்வு (Workflow)",
    "Admin": "நிர்வாகம் (Admin)",
    "Users": "பயனர்கள்",
    "Toggle Sidebar": "பக்கப்பட்டியை மாற்று",
    "New Chat": "புதிய அரட்டை",
    "MCP Configuration": "MCP கட்டமைப்பு",
    "Agents": "கடல்சார் நிபுணர் முகவர்கள்",
    "Create Agent": "முகவரை உருவாக்கு",
    "Create an agent": "முகவரை உருவாக்கு",
    "Create your own specialized AI agent or select from shared agents in the Agents page": "உங்கள் சொந்த கடல்சார் AI முகவரை உருவாக்குங்கள்",
    "Today": "இன்று (Today)",
    "Yesterday": "நேற்று (Yesterday)",
    "Previous 7 Days": "கடந்த 7 நாட்கள்",
    "Previous 30 Days": "கடந்த 30 நாட்கள்",
    "Theme": "தோற்றம் (Theme)",
    "Language": "மொழி (Language)",
    "Settings": "அமைப்புகள்",
    "Profile": "சுயவிவரம்",
    "Sign Out": "வெளியேறு",
    "Marketplace": "சந்தை (Marketplace)",
    "MCP Servers": "MCP சேவையகங்கள்",
    "Add Server": "சேவையகத்தைச் சேர்",
    "Add MCP Server": "MCP சேவையகத்தைச் சேர்",
    "Connect Your First Server": "உங்கள் முதல் சேவையகத்தை இணைக்கவும்",
    "Add MCP servers to unlock powerful AI integrations": "கடல்சார் AI ஒருங்கிணைப்புகளைப் பெற MCP சேவையகங்களைச் சேர்க்கவும்",
    "Cancel": "ரத்துசெய்",
    "Update": "புதுப்பி",
    "Continue": "தொடரவும்",
    "Success": "வெற்றி",
    "Delete": "நீக்கு",
    "Save": "சேமி",
    "Back": "பின்செல்",
    "Next": "அடுத்து",
    "Create": "உருவாக்கு",
    "Search...": "தேடு...",
    "Archive": "காப்பகம் (Archive)",
    "Add Archive": "காப்பகத்தைச் சேர்",
}

LANG_MAPS = {
    "mr": MARATHI_MAPPINGS,
    "hi": HINDI_MAPPINGS,
    "gu": GUJARATI_MAPPINGS,
    "ta": TAMIL_MAPPINGS,
}

def translate_node(node, mapping):
    if isinstance(node, dict):
        return {k: translate_node(v, mapping) for k, v in node.items()}
    elif isinstance(node, list):
        return [translate_node(v, mapping) for v in node]
    elif isinstance(node, str):
        # Exact match
        if node in mapping:
            return mapping[node]
        # Partial replacements
        for eng, trans in mapping.items():
            if eng.lower() == node.lower():
                return trans
        return node
    return node

for lang, mapping in LANG_MAPS.items():
    translated_data = translate_node(en_data, mapping)
    lang_file = f"messages/{lang}.json"
    with open(lang_file, "w", encoding="utf-8") as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)
    print(f"Deeply translated {lang}.json")
