import json
import os

with open('messages/en.json', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

TRANSLATIONS_FULL = {
    "mr": {
        "Good morning, {name}": "शुभ प्रभात, {name}",
        "Good afternoon, {name}": "शुभ दुपार, {name}",
        "Good evening, {name}": "शुभ संध्याकाळ, {name}",
        "Nice to see you again, {name}": "तुम्हाला पुन्हा भेटून आनंद झाला, {name}",
        "What are you working on today? {name}": "आज आपण काय काम करत आहात, {name}?",
        "Let me know when you're ready to begin.": "सुरुवात करायची असल्यास मला सांगा.",
        "What are your thoughts today?": "आज आपले काय विचार आहेत?",
        "Where would you like to start?": "आपण कुठून सुरुवात करू इच्छिता?",
        "What are you thinking? {name}": "तुम्ही काय विचार करत आहात, {name}?",
        "Ask anything or @mention": "काहीही विचारा किंवा @mention करा",
        "Toggle Temporary Chat": "तात्पुरती चॅट टॉगल करा",
        "Temporary Chat": "तात्पुरती चॅट",
        "Reset Chat": "चॅट रीसेट करा",
        "This chat won't be saved.": "ही चॅट जतन केली जाणार नाही.",
        "Feel free to ask anything temporarily": "काहीही मोकळेपणाने विचारा",
        "Searching the Web...": "वेबवर शोधत आहे...",
        "Searched the Web": "वेबवर शोधले",
        "Select a tool mode": "टूल मोड निवडा",
        "Tools Setup": "टूल्स सेटअप",
        "Tools": "टूल्स (Tools)",
        "Workflow": "कार्यप्रवाह (Workflow)",
        "Admin": "प्रशासन (Admin)",
        "Users": "वापरकर्ते",
        "Toggle Sidebar": "साइडबार टॉगल करा",
        "New Chat": "नवीन चॅट",
        "MCP Configuration": "MCP कॉन्फिगरेशन",
        "Agents": "सागरी तज्ञ एजंट्स",
        "Create Agent": "एजंट तयार करा",
        "Create an agent": "एजंट तयार करा",
        "Create your own agent": "तुमचा स्वतःचा एजंट तयार करा",
        "Create your own specialized AI agent or select from shared agents in the Agents page": "तुमचा स्वतःचा विशेष सागरी AI एजंट तयार करा किंवा एजंट्स पृष्ठावरून निवडा",
        "Today": "आज (Today)",
        "Yesterday": "काल (Yesterday)",
        "Previous 7 Days": "मागील ७ दिवस",
        "Previous 30 Days": "मागील ३० दिवस",
        "Theme": "थीम (Theme)",
        "Language": "भाषा (Language)",
        "Settings": "सेटिंग्ज",
        "Profile": "प्रोफाइल",
        "Sign Out": "बाहेर पडा (Sign Out)",
        "Marketplace": "मार्केटप्लेस (Marketplace)",
        "MCP Servers": "MCP सर्व्हर्स",
        "Add Server": "सर्व्हर जोडा",
        "Add MCP Server": "MCP सर्व्हर जोडा",
        "Connect Your First Server": "तुमचा पहिला सर्व्हर कनेक्ट करा",
        "Add MCP servers to unlock powerful AI integrations": "शक्तिशाली सागरी AI एकत्रीकरण अनलॉक करण्यासाठी MCP सर्व्हर्स जोडा",
        "Available MCP Servers": "उपलब्ध MCP सर्व्हर्स",
        "Save Configuration": "कॉन्फिगरेशन जतन करा",
        "Tools Test": "साधने चाचणी",
        "Archive": "अभिलेखागार (Archive)",
        "Add Archive": "संग्रह जोडा",
        "Archive Name": "संग्रहाचे नाव",
        "Archive Description": "संग्रह वर्णन",
        "No Archives": "कोणताही संग्रह आढळला नाही",
        "Create First Archive": "पहिला संग्रह तयार करा",
        "Cancel": "रद्द करा",
        "Update": "अपडेट करा",
        "Continue": "पुढे सुरू ठेवा",
        "Success": "यशस्वी",
        "Delete": "हटवा",
        "Save": "जतन करा",
        "Back": "मागे",
        "Next": "पुढे",
        "Create": "तयार करा",
        "Search...": "शोधा...",
        "Approve": "मंजूर करा",
        "Reject": "नाकारा",
        "Saving...": "जतन करत आहे...",
        "Optional": "पर्यायी",
        "Deleting...": "हटवत आहे...",
        "Run": "चालवा",
        "Description": "वर्णन",
        "Default Value": "डीफॉल्ट मूल्य",
        "Empty": "रिकामे",
        "Required": "आवश्यक",
        "Options": "पर्याय",
        "Status": "स्थिती",
        "Result": "निकाल",
        "Started At": "सुरू झाले",
        "Duration": "कालावधी",
        "Add Option": "पर्याय जोडा",
        "Tool": "साधन (Tool)",
        "Select Tool...": "साधन निवडा...",
        "No results.": "कोणतेही निकाल आढळले नाहीत.",
        "Generate With AI": "AI सह तयार करा"
    },
    "hi": {
        "Good morning, {name}": "शुभ प्रभात, {name}",
        "Good afternoon, {name}": "शुभ दोपहर, {name}",
        "Good evening, {name}": "शुभ संध्या, {name}",
        "Nice to see you again, {name}": "आपको दोबारा देखकर खुशी हुई, {name}",
        "What are you working on today? {name}": "आज आप किस पर काम कर रहे हैं, {name}?",
        "Let me know when you're ready to begin.": "जब आप तैयार हों तो मुझे बताएं।",
        "What are your thoughts today?": "आज आपके क्या विचार हैं?",
        "Where would you like to start?": "आप कहाँ से शुरुआत करना चाहेंगे?",
        "What are you thinking? {name}": "आप क्या सोच रहे हैं, {name}?",
        "Ask anything or @mention": "कुछ भी पूछें या @mention करें",
        "Toggle Temporary Chat": "अस्थायी चैट टॉगल करें",
        "Temporary Chat": "अस्थायी चैट",
        "Reset Chat": "चैट रीसेट करें",
        "This chat won't be saved.": "यह चैट सहेजी नहीं जाएगी।",
        "Feel free to ask anything temporarily": "कुछ भी पूछने के लिए स्वतंत्र महसूस करें",
        "Searching the Web...": "वेब पर खोज रहा है...",
        "Searched the Web": "वेब पर खोजा गया",
        "Select a tool mode": "टूल मोड चुनें",
        "Tools Setup": "टूल्स सेटअप",
        "Tools": "टूल्स (Tools)",
        "Workflow": "कार्यप्रवाह (Workflow)",
        "Admin": "प्रशासन (Admin)",
        "Users": "उपयोगकर्ता",
        "Toggle Sidebar": "साइडबार टॉगल करें",
        "New Chat": "नई चैट",
        "MCP Configuration": "MCP विन्यास",
        "Agents": "समुद्री विशेषज्ञ एजेंट",
        "Create Agent": "एजेंट बनाएं",
        "Create an agent": "एजेंट बनाएं",
        "Create your own agent": "अपना एजेंट बनाएं",
        "Create your own specialized AI agent or select from shared agents in the Agents page": "अपना विशेष समुद्री AI एजेंट बनाएं या एजेंट पेज से चुनें",
        "Today": "आज (Today)",
        "Yesterday": "कल (Yesterday)",
        "Previous 7 Days": "पिछले 7 दिन",
        "Previous 30 Days": "पिछले 30 दिन",
        "Theme": "थीम (Theme)",
        "Language": "भाषा (Language)",
        "Settings": "सेटिंग्स",
        "Profile": "प्रोफ़ाइल",
        "Sign Out": "साइन आउट",
        "Marketplace": "मार्केटप्लेस",
        "MCP Servers": "MCP सर्वर",
        "Add Server": "सर्वर जोड़ें",
        "Add MCP Server": "MCP सर्वर जोड़ें",
        "Connect Your First Server": "अपना पहला सर्वर कनेक्ट करें",
        "Add MCP servers to unlock powerful AI integrations": "शक्तिशाली समुद्री AI एकीकरण के लिए MCP सर्वर जोड़ें",
        "Available MCP Servers": "उपलब्ध MCP सर्वर",
        "Save Configuration": "विन्यास सहेजें",
        "Tools Test": "उपकरण परीक्षण",
        "Archive": "अभिलेखागार (Archive)",
        "Add Archive": "संग्रह जोड़ें",
        "Archive Name": "संग्रह का नाम",
        "Archive Description": "संग्रह विवरण",
        "No Archives": "कोई संग्रह नहीं मिला",
        "Create First Archive": "पहला संग्रह बनाएं",
        "Cancel": "रद्द करें",
        "Update": "अपडेट करें",
        "Continue": "जारी रखें",
        "Success": "सफल",
        "Delete": "हटाएं",
        "Save": "सहेजें",
        "Back": "पीछे",
        "Next": "आगे",
        "Create": "बनाएं",
        "Search...": "खोजें...",
        "Approve": "स्वीकृत करें",
        "Reject": "अस्वीकार करें",
        "Saving...": "सहेजा जा रहा है...",
        "Optional": "वैकल्पिक",
        "Deleting...": "हटाया जा रहा है...",
        "Run": "चलाएं",
        "Description": "विवरण",
        "Default Value": "डिफ़ॉल्ट मान",
        "Empty": "खाली",
        "Required": "आवश्यक",
        "Options": "विकल्प",
        "Status": "स्थिति",
        "Result": "परिणाम",
        "Started At": "शुरू हुआ",
        "Duration": "अवधि",
        "Add Option": "विकल्प जोड़ें",
        "Tool": "उपकरण (Tool)",
        "Select Tool...": "उपकरण चुनें...",
        "No results.": "कोई परिणाम नहीं मिला।",
        "Generate With AI": "AI के साथ उत्पन्न करें"
    }
}

def translate_node(node, mapping):
    if isinstance(node, dict):
        return {k: translate_node(v, mapping) for k, v in node.items()}
    elif isinstance(node, list):
        return [translate_node(v, mapping) for v in node]
    elif isinstance(node, str):
        if node in mapping:
            return mapping[node]
        for eng, trans in mapping.items():
            if eng.strip().lower() == node.strip().lower():
                return trans
        return node
    return node

for lang, mapping in TRANSLATIONS_FULL.items():
    res = translate_node(en_data, mapping)
    with open(f"messages/{lang}.json", "w", encoding="utf-8") as f:
        json.dump(res, f, ensure_ascii=False, indent=2)
    print(f"Updated messages/{lang}.json successfully!")
